name: Run pytest
on: [push]

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: test in pipenv
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run python -m pytest
